name: torrenttools
on:
  workflow_dispatch
    inputs:
      name:
        description: Name of the torrent file
        required: true
        default: adobe
      comment:
        description: Comment
        required: true
        default: Adobe Master Collection 2019 RUS-ENG v7 by torrent-webseed-creator
      url:
        description: URL of the file
        required: true
        default: 'https://51-15-165-111.arfiles.net/Adobe%20Master%20Collection%202019%20RUS-ENG%20v7.zip'
      file_name:
        description: File name of the file in the torrent
        required: true
        default: Adobe_Master_Collection_2019_RUS-ENG_v7.zip
      piece_size:
        description: Piece Size. Use auto for automatic calculation, or use the recommended piece size on the README.md file
        required: true
        default: auto
      protocol_version:
        description: BitTorrent Protocol version 1, 2, or hybrid
        required: true
        default: '1'
      maximize_disk_space:
        description: Maximize disk space. Set to true if getting out of disk space error
        default: 'false'

jobs:
  create_torrent:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize disk space
        if: ${{ github.event.inputs.maximize_disk_space == 'true' }}
        uses: easimon/maximize-build-space@v4
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Install torrenttools
        run: |
          sudo add-apt-repository ppa:fbdtemme/torrenttools
          sudo apt-get update
          sudo apt-get install torrenttools

      - name: Download file
        run: aria2c -x 16 -o "${{ github.event.inputs.file_name }}" "${{ github.event.inputs.url }}"

      - name: Create torrent using torrenttools
        run: torrenttools create -v "${{ github.event.inputs.protocol_version }}" -o "${{ github.event.inputs.name }}.torrent" -w "${{ github.event.inputs.url }}" -c "${{ github.event.inputs.comment }}" -l "${{ github.event.inputs.piece_size }}" -s "torrent-webseed-creator" "${{ github.event.inputs.file_name }}"

      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.name }}
          path: ${{ github.event.inputs.name }}.torrent
